/* Offline machinery for the whole site. Generated by
   build/build_site.py; do not edit by hand, the next build overwrites it.
   Two caches with different lifetimes: CORE precaches the installable tools
   and the site shell, and its versioned name retires it whenever a cached
   file changes. PAGES holds everything a reader has visited, plus the full
   offline copy if they asked for one; it survives version bumps because its
   contents are refreshed network-first on every online visit anyway. */
const VERSION = "41db6564702c";
const CORE    = "site-" + VERSION;
const PAGES   = "site-pages-v1";
const FILES   = [
  "daily-learning-cockpit-192.png",
  "daily-learning-cockpit-512.png",
  "daily-learning-cockpit.html",
  "daily-learning-cockpit.webmanifest",
  "law-arena-192.png",
  "law-arena-512.png",
  "law-arena.html",
  "law-arena.webmanifest",
  "skill-forge-192.png",
  "skill-forge-512.png",
  "skill-forge.html",
  "skill-forge.webmanifest"
];

self.addEventListener("install", e => {
  e.waitUntil(
    caches.open(CORE)
      // addAll is all-or-nothing, so one missing file would leave the tools
      // with no cache at all. Each file is added on its own and a failure is
      // survivable: the rest still work offline.
      .then(c => Promise.all(FILES.map(f => c.add(f).catch(() => null))))
      .then(() => self.skipWaiting())
  );
});

self.addEventListener("activate", e => {
  e.waitUntil(
    caches.keys()
      .then(keys => Promise.all(
        keys.filter(k => k !== CORE && k !== PAGES).map(k => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", e => {
  const req = e.request;
  if (req.method !== "GET") return;
  const url = new URL(req.url);
  if (url.origin !== location.origin) return;

  // Cache first, refresh behind: a click on a saved page opens from disk
  // with no network wait at all, while the fetch that follows replaces the
  // stored copy so the next click is current. A page seen after a publish
  // is therefore at most one visit old, and never slow.
  e.respondWith(
    caches.match(req).then(hit => {
      const refresh = fetch(req)
        .then(res => {
          if (res && res.ok && res.type === "basic") {
            const copy = res.clone();
            caches.open(PAGES).then(c => c.put(req, copy)).catch(() => {});
          }
          return res;
        });
      if (hit) { refresh.catch(() => {}); return hit; }
      return refresh.catch(() =>
        caches.match(url.pathname.replace(/^\//, "") || "index.html")
          .then(h2 => h2 || caches.match("index.html")));
    })
  );
});

/* The full offline copy: a page posts cache-all and the worker walks the
   build-generated manifest, reporting progress so the button can count.
   drop-all removes the copy (and everything visited) in one motion. */
self.addEventListener("message", e => {
  const msg = e.data || {};
  const tell = m => { if (e.source) e.source.postMessage(m); };
  if (msg.type === "cache-all") {
    e.waitUntil((async () => {
      let man;
      try {
        man = await (await fetch("offline-manifest.json", {cache: "no-cache"})).json();
      } catch (err) { tell({type: "cache-all-done", ok: 0, failed: -1}); return; }
      const c = await caches.open(PAGES);
      let ok = 0, failed = 0;
      const files = man.files || [];
      const pool = 6;
      let i = 0;
      async function worker() {
        while (i < files.length) {
          const f = files[i++];
          try {
            const res = await fetch(f, {cache: "no-cache"});
            if (res && res.ok) { await c.put(f, res); ok++; }
            else failed++;
          } catch (err) { failed++; }
          if ((ok + failed) % 5 === 0 || ok + failed === files.length)
            tell({type: "cache-all-progress", done: ok + failed, total: files.length});
        }
      }
      await Promise.all(Array.from({length: pool}, worker));
      tell({type: "cache-all-done", ok, failed, total: files.length});
    })());
  } else if (msg.type === "drop-all") {
    e.waitUntil(caches.delete(PAGES).then(() => tell({type: "drop-all-done"})));
  }
});
